### ISSUE TITLE
Cannot connect to Safari corporate account authorised by sos (redirecting to corporate authentication)

### ISSUE THREAD

**Issue by milan496** [nicohaenggi/SafariBooks-Downloader#39] opened 2018-11-05 08:39 UTC
Hello I am getting an error safari-downloader] StatusCodeError: 400 - {"error":"invalid_grant","error_description":"Invalid credentials given."}
I have corporate account on safari - it means when sign in into safari online I can only fill in username/email and immediately I am redirected to corporate sign in page to authorise  - can it be solved somehow in safari downloader?

**Comment by nicohaenggi** [comment] 2019-01-16 23:13
thanks for reporting this. unfortunately, this is not supported as of right now. please refer to pull request #32 or #21 for possible implementations. I'm closing this issues since there is already an open issue #4 about this.

**Comment by nicohaenggi** [comment] 2019-01-16 23:14
#4

**Comment by nicohaenggi** [comment] 2019-01-16 23:15
duplicate of #4

**Closed by nicohaenggi** 2019-01-16 23:15 UTC
Labels: duplicate

**Comment by nicohaenggi** [comment] 2019-01-16 23:17
Duplicate of #4

**Comment by milan496** [comment] 2019-01-17 07:59
Thank you for a replay, in a meantime I found in some other request 
workaround using info from cookies which works for me.

Milan Rafaj
=============================================
Infrastructure Architects & Specialists Teamleader
Global Technology Services, CEE
Tel: +420 27213 1356 Fax: +420 27213 1144
Mobile:+420 737 264 248
External e-mail: milan_rafaj@cz.ibm.com
WWW:ibm.cz
IBM Services

IBM Česká republika, spol. s r.o.
Sídlo: Praha 4, Chodov, V Parku č.or.4,č.p.2294, PSČ 14800
IČ: 14890992
Zapsaná v obchodním rejstříku, vedeném Městským soudem v Praze oddíl C, 
vložka 692

IBM Ceska republika, spol. s r. o.
Registered address: Prague 4, Chodov, V Parku 2294/4, Zip Code: 148 00
Company ID: 14890992
Entered in the Commercial Register maintained by the Municipal Court in 
Prague (Part C, Entry 692)
