### ISSUE TITLE
RequestError: Error: connect ETIMEDOUT 151.101.113.132:443

### ISSUE THREAD

**Issue by PlonkaAdam** [nicohaenggi/SafariBooks-Downloader#13] opened 2018-01-07 22:39 UTC
I get this error after downloading table of content files

RequestError: Error: connect ETIMEDOUT 151.101.113.132:443

**Comment by Purus** [comment] 2018-01-09 18:14
+1 I also get the same issue.

**Comment by nicohaenggi** [comment] 2018-01-12 12:42
Duplicate of #10

**Closed** 2018-01-12 12:43 UTC
Labels: duplicate
