### ISSUE TITLE
SSO support

### ISSUE THREAD

**Issue by tomd8451** [nicohaenggi/SafariBooks-Downloader#18] opened 2018-02-21 16:29 UTC
I have a SSO account setup with Safari, so I can't specify a password. When logging into Safari, after typing in my email I am redirected to my SSO screen to login with my credentials. Ultimately would love some form of being able to specify that I use SSO and have SafariBooks-Downloader pop up a browser window for me to log in and capture the cookie returned for subsequent requests.

**Comment by frayos** [comment] 2018-02-22 09:11
+1

**Comment by nicohaenggi** [comment] 2018-03-28 16:56
Duplicate of #4

**Closed by nicohaenggi** 2018-03-28 16:56 UTC
Labels: duplicate
